# Generated by Django 6.1 on 2026-08-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="default_user",
                max_length=150,
                unique=True,
                verbose_name="Имя пользователя",
            ),
            preserve_default=False,
        ),
    ]
