# Generated by Django 6.1 on 2026-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True, verbose_name="Имя пользователя"),
        ),
    ]
