# Generated by Django 6.1 on 2026-08-15 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="end_time",
            field=models.DateTimeField(
                default="2026-01-01 00:00:00",
                help_text="Укажите дату и время окончания рассылки",
                verbose_name="Дата и время окончания отправки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 8, 15, 12, 55, 35, 867234, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату и время начала рассылки",
                verbose_name="Дата и время начала отправки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("completed", "Завершена"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
